//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities
    {
        public cities()
        {
            this.seo_place = new HashSet<seo_place>();
        }
    
        public long id { get; set; }
        public long country_id { get; set; }
        public Nullable<int> areaId { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string casePrepositional { get; set; }
        public string caseDative { get; set; }
        public string caseGenitive { get; set; }
        public long pos { get; set; }
        public decimal latitude { get; set; }
        public sbyte coded { get; set; }
        public decimal longitude { get; set; }
    
        public virtual area area { get; set; }
        public virtual ICollection<seo_place> seo_place { get; set; }
    }
}
