//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class companies
    {
        public companies()
        {
            this.import_rectangle = new HashSet<import_rectangle>();
            this.mockup_set = new HashSet<mockup_set>();
        }
    
        public long id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string passwd { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public long country_id { get; set; }
        private string zip { get; set; }
        private string phone { get; set; }
        private string phone2 { get; set; }
        private string email { get; set; }
        private string bank { get; set; }
        private string bank_account { get; set; }
        private string edrpou { get; set; }
        private string address_law { get; set; }
        private string prefix { get; set; }
        private long reserve_hours { get; set; }
        private long users_limit { get; set; }
        private bool autoconfirm { get; set; }
        private string contract { get; set; }
        private bool is_active { get; set; }
        private bool showResourcesWhileInactive { get; set; }
        private sbyte use_reserves { get; set; }
        private sbyte deny_next_year { get; set; }
        private string sync_url { get; set; }
        private Nullable<System.DateTime> sync_date { get; set; }
        private Nullable<int> sync_resources { get; set; }
        private Nullable<int> sync_new_resources { get; set; }
        private Nullable<int> sync_periods { get; set; }
        private string sync_files { get; set; }
        private string lose_date { get; set; }
        private Nullable<System.DateTime> to_period { get; set; }
        private sbyte tax { get; set; }
        private bool deny_map { get; set; }
        private string code_free { get; set; }
        private string code_reserved { get; set; }
        private string code_reserve { get; set; }
        private bool new_codes { get; set; }
        private string ownMediaUrl { get; set; }
        private string requisites { get; set; }
        private bool syncCheckLimit { get; set; }
    
        public virtual ICollection<import_rectangle> import_rectangle { get; set; }
        public virtual ICollection<mockup_set> mockup_set { get; set; }
    }
}
