//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class import_rectangle
    {
        public long id { get; set; }
        public long companyId { get; set; }
        public string type { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public short x1 { get; set; }
        public short y1 { get; set; }
        public short x2 { get; set; }
        public short y2 { get; set; }
    
        public virtual companies companies { get; set; }
    }
}
