//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class mockup_set
    {
        public mockup_set()
        {
            this.mockup = new HashSet<mockup>();
        }
    
        public long id { get; set; }
        public string hash { get; set; }
        public string emailClient { get; set; }
        public string emailManager { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<long> companyId { get; set; }
        public byte withPreview { get; set; }
        public System.DateTime dateCreate { get; set; }
        public Nullable<System.DateTime> dateValid { get; set; }
    
        public virtual companies companies { get; set; }
        public virtual ICollection<mockup> mockup { get; set; }
        public virtual users users { get; set; }
    }
}
