//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public long id { get; set; }
        public long user_id { get; set; }
        public long subuser_id { get; set; }
        public System.DateTime added { get; set; }
        public System.DateTime changed { get; set; }
        public System.DateTime expires { get; set; }
        public string status { get; set; }
        public string comments { get; set; }
    }
}
