//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_confirms
    {
        public long order_id { get; set; }
        public long resource_id { get; set; }
        public decimal price_actual { get; set; }
        public decimal subprice_actual { get; set; }
        public decimal discount_actual { get; set; }
        public decimal discount_qty_actual { get; set; }
    }
}
