//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo_report_resource
    {
        public photo_report_resource()
        {
            this.photo_report_resource_photo = new HashSet<photo_report_resource_photo>();
        }
    
        public long id { get; set; }
        public long reportId { get; set; }
        public long resourceId { get; set; }
    
        public virtual photo_report photo_report { get; set; }
        public virtual resources resources { get; set; }
        public virtual ICollection<photo_report_resource_photo> photo_report_resource_photo { get; set; }
    }
}
