//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo_report
    {
        public photo_report()
        {
            this.photo_report_resource = new HashSet<photo_report_resource>();
        }
    
        public long id { get; set; }
        public Nullable<long> userId { get; set; }
        public bool showLocations { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<photo_report_resource> photo_report_resource { get; set; }
    }
}
