//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class photo_report_resource_photo
    {
        public long id { get; set; }
        public long parentId { get; set; }
        public string photo { get; set; }
        public short sort { get; set; }
    
        public virtual photo_report_resource photo_report_resource { get; set; }
    }
}
