//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class presentation_link
    {
        public presentation_link()
        {
            this.presentation_link_resource = new HashSet<presentation_link_resource>();
        }
    
        public long id { get; set; }
        public string type { get; set; }
        public Nullable<long> userId { get; set; }
        public string hash { get; set; }
        public int downloadCount { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<System.DateTime> dateLastDownload { get; set; }
        public string vars { get; set; }
    
        public virtual users users { get; set; }
        public virtual ICollection<presentation_link_resource> presentation_link_resource { get; set; }
    }
}
