//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource_price_rules
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public int agency_id { get; set; }
        public decimal price_from { get; set; }
        public decimal price_to { get; set; }
        public Nullable<decimal> percent { get; set; }
        public Nullable<decimal> bonus { get; set; }
    }
}
