//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource_import_log
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public string filename { get; set; }
        public string errors { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public bool status { get; set; }
    }
}
