//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource_types
    {
        public resource_types()
        {
            this.seo_place = new HashSet<seo_place>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public long pos { get; set; }
        public string view { get; set; }
        public string view_north { get; set; }
        public string view_north_east { get; set; }
        public string view_east { get; set; }
        public string view_east_south { get; set; }
        public string view_south { get; set; }
        public string view_west { get; set; }
        public string view_north_west { get; set; }
        public string view_south_west { get; set; }
        public string view_bot { get; set; }
        public string view_agency { get; set; }
        public string view_north_agency { get; set; }
        public string view_north_east_agency { get; set; }
        public string view_east_agency { get; set; }
        public string view_east_south_agency { get; set; }
        public string view_south_agency { get; set; }
        public string view_west_agency { get; set; }
        public string view_north_west_agency { get; set; }
        public string view_south_west_agency { get; set; }
        public string iconBot { get; set; }
        public string iconOperator { get; set; }
        public string iconAgency { get; set; }
    
        public virtual ICollection<seo_place> seo_place { get; set; }
    }
}
