//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class subresources_history
    {
        public int company_id { get; set; }
        public int resource_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime changed { get; set; }
        public decimal price { get; set; }
    }
}
