//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync
    {
        public int id { get; set; }
        public int company_id { get; set; }
        public int resource_id { get; set; }
        public System.DateTime period { get; set; }
        public string status { get; set; }
        public System.DateTime added { get; set; }
    }
}
