//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class synonym_word
    {
        public synonym_word()
        {
            this.synonym_word1 = new HashSet<synonym_word>();
            this.synonym_word2 = new HashSet<synonym_word>();
        }
    
        public long id { get; set; }
        public bool isMain { get; set; }
        public string word { get; set; }
    
        public virtual ICollection<synonym_word> synonym_word1 { get; set; }
        public virtual ICollection<synonym_word> synonym_word2 { get; set; }
    }
}
