//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tooltip
    {
        public int id { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string name { get; set; }
        public string caption { get; set; }
        public string text { get; set; }
    
        public virtual tooltip_category tooltip_category { get; set; }
    }
}
