//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tooltip_category
    {
        public tooltip_category()
        {
            this.tooltip = new HashSet<tooltip>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string caption { get; set; }
        public short sort { get; set; }
    
        public virtual ICollection<tooltip> tooltip { get; set; }
    }
}
