//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_history
    {
        public long user_id { get; set; }
        public System.DateTime changed { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string icq { get; set; }
        public string skype { get; set; }
        public string c_company { get; set; }
        public string c_address { get; set; }
        public string c_city { get; set; }
        public string c_region { get; set; }
        public long c_country_id { get; set; }
        public string c_zip { get; set; }
        public string c_email { get; set; }
        public string c_phone { get; set; }
        public string c_phone2 { get; set; }
        public string c_bank { get; set; }
        public string c_bank_account { get; set; }
        public string c_edrpou { get; set; }
        public string c_address_law { get; set; }
        public string c_properties { get; set; }
    }
}
