//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.mockup_set = new HashSet<mockup_set>();
            this.photo_report = new HashSet<photo_report>();
            this.presentation_link = new HashSet<presentation_link>();
        }
    
        public long id { get; set; }
        public long company_id { get; set; }
        public Nullable<long> manager_id { get; private set; }
        public string login { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        private string icq { get; set; }
        private string skype { get; set; }
        public string type { get; set; }
        private string wannabe { get; set; }
        private bool is_private { get; set; }
        private bool is_active { get; set; }
        private bool is_banned { get; set; }
        private string token { get; set; }
        private System.DateTime added { get; set; }
        private bool ip_check { get; set; }
        private long ip { get; set; }
        private sbyte is_default { get; set; }
        private int last_user { get; set; }
        private sbyte is_price_visible { get; set; }
        private bool translitPresentation { get; set; }
        private string useBefore { get; set; }
    
        public virtual ICollection<mockup_set> mockup_set { get; set; }
        public virtual ICollection<photo_report> photo_report { get; set; }
        public virtual ICollection<presentation_link> presentation_link { get; set; }
    }
}
