//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_clients
    {
        public long user_id { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string region { get; set; }
        public long country_id { get; set; }
        public string zip { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string phone2 { get; set; }
        public string bank { get; set; }
        public string bank_account { get; set; }
        public string edrpou { get; set; }
        public string address_law { get; set; }
        public string properties { get; set; }
    }
}
