//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte HeaderSearchAlgorithm {
            get {
                return ((byte)(this["HeaderSearchAlgorithm"]));
            }
            set {
                this["HeaderSearchAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public uint HeaderSearchAlgorithm_2_MaxHeaderCount {
            get {
                return ((uint)(this["HeaderSearchAlgorithm_2_MaxHeaderCount"]));
            }
            set {
                this["HeaderSearchAlgorithm_2_MaxHeaderCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public uint HeaderSearchAlgorithm_2_MaxCellsFillCount {
            get {
                return ((uint)(this["HeaderSearchAlgorithm_2_MaxCellsFillCount"]));
            }
            set {
                this["HeaderSearchAlgorithm_2_MaxCellsFillCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|][\':<>?*&^%$#@!`~+=_")]
        public string HeaderSearchAlgorithm_2_BadSymbols {
            get {
                return ((string)(this["HeaderSearchAlgorithm_2_BadSymbols"]));
            }
            set {
                this["HeaderSearchAlgorithm_2_BadSymbols"] = value;
            }
        }
    }
}
