//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExelConverter.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte HeaderSearchAlgorithm {
            get {
                return ((byte)(this["HeaderSearchAlgorithm"]));
            }
            set {
                this["HeaderSearchAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public uint HeaderSearchAlgorithm_2_MaxHeaderCount {
            get {
                return ((uint)(this["HeaderSearchAlgorithm_2_MaxHeaderCount"]));
            }
            set {
                this["HeaderSearchAlgorithm_2_MaxHeaderCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public uint HeaderSearchAlgorithm_2_MaxCellsFillCount {
            get {
                return ((uint)(this["HeaderSearchAlgorithm_2_MaxCellsFillCount"]));
            }
            set {
                this["HeaderSearchAlgorithm_2_MaxCellsFillCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("|][\':<>?*&^%$#@!`~+=_")]
        public string HeaderSearchAlgorithm_2_BadSymbols {
            get {
                return ((string)(this["HeaderSearchAlgorithm_2_BadSymbols"]));
            }
            set {
                this["HeaderSearchAlgorithm_2_BadSymbols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint MaxRowsInGroupCountToDeleteSimilarityRows {
            get {
                return ((uint)(this["MaxRowsInGroupCountToDeleteSimilarityRows"]));
            }
            set {
                this["MaxRowsInGroupCountToDeleteSimilarityRows"] = value;
            }
        }
    }
}
